### ISSUE TITLE
Error when running on Mac

### ISSUE THREAD

**Issue by srb0203** [dribnet/plat#4] opened 2017-08-11 23:00 UTC
plat sample --model celeba_64.discgen
Loading DiscGenModel interface from discgen.interface
Loading model celeba_64.discgen
Traceback (most recent call last):
  File "/Users/saurabhmishra/anaconda/bin/plat", line 11, in <module>
    sys.exit(main())
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/plat/bin/platcmd.py", line 12, in main
    handler.run()
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/arghandler/base.py", line 295, in run
    self._subcommand_lookup[args.cmd](scmd_parser,context,args.cargs)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/plat/bin/sample.py", line 256, in sample
    run_with_args(args, dmodel, args.anchor_image, args.save_path, cur_z_step)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/plat/bin/sample.py", line 67, in run_with_args
    dmodel = zoo.load_model(args.model, args.model_file, args.model_type, args.model_interface)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/plat/zoo.py", line 72, in load_model
    return load_model_with_interface(model_file_name, model_interface)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/plat/zoo.py", line 50, in load_model_with_interface
    model = ModelClass(filename=model_file_name)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/discgen/interface.py", line 60, in __init__
    self.model = Model(load(src).algorithm.cost)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/blocks/serialization.py", line 277, in load
    return p.load()
  File "/Users/saurabhmishra/anaconda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/pickle.py", line 902, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/blocks/serialization.py", line 600, in __call__
    components = _unmangle_parameter_name(id_)
  File "/Users/saurabhmishra/anaconda/lib/python2.7/site-packages/blocks/serialization.py", line 633, in _unmangle_parameter_name
    return _INVERSE_ARRAY_TYPE_MAP[type_], context_name, name
KeyError: 'cuda_ndarray'

I am getting this error when I try to run the program on a MacBook Pro. Any solutions for this? I have tried to find online what could be the reason for this but haven't had any success.

**Comment by dribnet** [comment] 2018-04-01 08:29
The serialized models I used for this were based on the `blocks` library and serialization errors were commonly caused by not having cuda enabled (since cuda is needed to deserialize some objects) and even slightly different versions of Theano. I've decided to deprecate these models and will be switching to tensorflow models, hopefully using tensflow-hub.

Note that the library will still support pytorch, etc. but the built in models would be specific to Tensorflow.

Sorry about these problems you had trying to get this working on your mac. If you are still interested in trying this out let me know - this issue should hopefully be fixed with the next release later this month.

**Closed as completed by dribnet** 2018-04-01 08:29 UTC
